#
# HMCCosmetics Configuration (Remapped)
#
config-version: 1

default-menu: defaultmenu
debug-mode: false
database-settings:
  type: sqlite #MYSQL, SQLite
  mysql:
    database: database
    password: cherryBomb
    port: 3306
    host: localhost
    user: username
  delay:
    enabled: false # This is for if other plugins need to handle certain aspects of a player first.
    delay: 20 # In ticks
cosmetic-settings:
  tick-period: 20 # In ticks, determines how many times a player cosmetics should be updated. -1 to disable.
  # Ticking periods is something that ensures new players near a player get the packets to actually apply to the user.

  unapply-on-death: false # If when a player dies, their cosmetics should be unapplied. If this is true, use hmccosmetics.unapplydeath.bypass to bypass
  force-permission-join: true # Checks a player permission if they can have a cosmetic when they join the server.
  force-show-join: false # If the plugin should force show a player's cosmetics when they join the server.

  emote-distance: -3 # This shows how far away the camera should be while a player is doing an emote. Negative is behind player.
  emote-block-check: true # If the server should check if the block is open where the camera is placed (prevents players viewing through blocks)
  emote-air-check: true # Check if there is air under a player, if there is, don't play emote
  emote-damage-leave: true # If the player should leave the emote when they take damage
  emote-invincible: false # If the player should not take damage while doing an emote
  # If a player should be put into camera mode when looking at an emote. Highly recommend keeping it as true.
  emote-camera: true
  # If a player should be able to move in an emote. This option really only affects if "emote-camera" is false
  emote-move: false
  # This make it so it always sends the riding packets for the backpack. This sends more packets but is more reliable for servers which modify player passengers.
  backpack-force-riding-packet: false

  helmet-add-enchantments: false # If the plugin should keep enchants on helmets. This is useful as some enchantments are client side only.
  chest-add-enchantments: false # If the plugin should keep enchants on chestplate. This is useful as some enchantments are client side only.
  leggings-add-enchantments: false # If the plugin should keep enchants on leggings. This is useful as some enchantments are client side only.
  boots-add-enchantments: false # If the plugin should keep enchants on boots. This is useful as some enchantments are client side only.

  # This attempts to destroy cosmetics that get loose in the wild, such as through a player entering creative mode.
  # Most servers who don't use creative mode and have properly set up the plugin should have no need for this and can leave it disabled.
  destroy-loose-cosmetics: false

  # view distance in blocks that other players will see the backpack cosmetic
  # setting this to lower than the server player view distance should fix the
  # bug where players see random backpacks. Put -1 to ignore and send packets to everyone.
  view-distance: 32
  # how the balloon should be positioned relative to the player
  balloon-offset:
    x: 0.5
    y: 3
    z: 0.5
menu-settings:
  shading:
    # Below is the shading mechanism behind cosmetic items. This is a bit complicated, but it allows for a lot of customization.
    # The shading is done through the title and by shifting textures around. This is done by offsets.
    # Vanilla, ItemsAdder, and Oraxen are supported **BUT** requires some manual work. Default values are Vanilla. See below.
    enabled: false # Default of menus having shading. This can be toggled individually in menus with "shading: true/false"
    first-row-shift: "<s:-169>" # Oraxen: "<s:-169>"
    sequent-row-shift: " <s:-169>" # Oraxen: " <s:-169>" (Space is important here!)
    individual-column-shift: "<s:-3>" # Oraxen: "<s:-3>"
    background: "<g:shade_row_<row>:colorable> " # Oraxen: "<g:shade_row_<row>:colorable> 
    clear-background: "<g:clear_row_<row>:colorable> " # Oraxen: "<g:clear_row_<row>:colorable> "
    #These use MiniMessage for color! https://docs.advntr.dev/minimessage/format.html#color
    equipped-cosmetic-color: "<yellow>"
    equipable-cosmetic-color: "<green>"
    locked-cosmetic-color: "<red>"
  cosmetic-type:
    # This allows you to specify if it should require a special click type for the interaction to work.
    equip-click: "ANY" # ANY or ClickType, https://jd.papermc.io/paper/1.20/org/bukkit/event/inventory/ClickType.html
    unequip-click: "ANY" # ANY or ClickType, https://jd.papermc.io/paper/1.20/org/bukkit/event/inventory/ClickType.html
dye-menu:
  # If you use ItemsAdder, set this to "§f:offset_-8::dye_menu:"
  # If you use Oraxen, set this to "<glyph:neg_shift_8><glyph:dye_menu>"
  title: "§f"
  input-slot: 19
  output-slot: 25
hook-settings:
  itemsadder:
    # This causes the plugin to reload itself after any ItemsAdder change. This keeps the plugin fully up to date with IA, but
    # could cause console spam as HMCCosmetics has to reload itself as well.
    reload-on-change: false
  worldguard:
    # Checks worldguard regions for HMCC flags. If set to false, flags will not work properly.
    # Requires restart to apply changes.
    player-move-check: true
wardrobe:
  # spawn static wardrobe if in this radius of wardrobe-location
  static-radius: 10
  # how much yaw should change per tick, set to 0 for none
  rotation-speed: 3
  # Applies a pumpkin for an overlay of the player while in the wardrobe.
  equip-pumpkin: false
  # Rather than having a set exit location, this will send the player back to where they entered the wardrobe. Not recommended for WG regions
  return-last-location: false
  # If players in wardrobes should be able to equip any cosmetic, regardless of permission (Cosmetics they do not have access to will be removed when they leave the wardrobe)
  unchecked-wardrobe-cosmetics: false

  menu-options:
    enter-open-menu: false # If the menu should open when a player enters a wardrobe

  gamemode-options:
    exit-gamemode-enabled: false # Setting this to false will set the gamemode the player came in as. True sets to exit-gamemode gamemode
    exit-gamemode: "SURVIVAL" # Only activates if exit-gamemode-enabled is true, find gamemodes here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/GameMode.html

  # Bossbar that shows when a player is in a wardrobe.
  bossbar:
    enabled: false
    text: "Left-Click to open the menu!"
    progress: 1.0 # Goes between 0.0 -> 1.0
    overlay: PROGRESS
    color: BLUE
  transition:
    enabled: true
    # If you use ItemsAdder, set this to "<black>%img_title%
    # If you use Oraxen, set this to "<black><glyph:title>"
    text: "<black>"
    delay: 40
    title-fade-in: 1000 # milliseconds
    title-stay: 500 # milliseconds
    title-fade-out: 1000 # milliseconds
  wardrobes:
    default:
      npc-location:
        world: "world"
        x: 0
        y: 0
        z: 0
        yaw: 0
        pitch: 0
      viewer-location:
        world: "world"
        x: 5
        y: 0
        z: 5
        yaw: 0
        pitch: 0
      leave-location:
        world: "world"
        x: 5
        y: 5
        z: 5
        yaw: 0
        pitch: 0
